In [76]:
import pickle 

def load_pkl(file):
    with open(file, 'rb') as file:
        return pickle.load(file)

In [77]:
ROOT_DIR = '/home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK'

DATASETS = ['helena', 'moa', 'rf1']

K = [1, 10, 20]

MODELS = ['hb', 'pb', 'hb15']

FOLDS = list(range(5))

In [78]:
from itertools import product
import os 
import pandas as pd

all_results = []
KEYS = ['dataset', 'k', 'model']

for dataset, k, model, fold in product(DATASETS, K, MODELS, FOLDS):
    path = os.path.join(ROOT_DIR, dataset, model, f'topk_{k}', f'fold_{fold}', 'results.pkl')
    if not os.path.exists(path):
        print(f'Skipped {path}')
        continue
    
    results = load_pkl(path)
    all_results.append(
        dict(zip(KEYS, (dataset, k, model))) | results
    )

all_results = pd.DataFrame(all_results)

Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/helena/hb15/topk_1/fold_1/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/helena/hb15/topk_10/fold_0/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/helena/hb15/topk_10/fold_1/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/helena/hb15/topk_10/fold_2/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/helena/hb15/topk_10/fold_3/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/helena/hb15/topk_10/fold_4/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/helena/hb15/topk_20/fold_0/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/helena/hb15/topk_20/fold_1/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/helena/hb15/topk_20/fold_2/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/helena/hb15/topk_20/fold_3/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/helena/hb15/topk_20/fold_4/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/moa/hb15/topk_1/fold_0/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/moa/hb15/topk_1/fold_1/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/moa/hb15/topk_1/fold_2/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/moa/hb15/topk_1/fold_3/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/moa/hb15/topk_1/fold_4/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/moa/hb15/topk_10/fold_0/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/moa/hb15/topk_10/fold_1/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/moa/hb15/topk_10/fold_2/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/moa/hb15/topk_10/fold_3/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/moa/hb15/topk_10/fold_4/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/moa/hb15/topk_20/fold_0/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/moa/hb15/topk_20/fold_1/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/moa/hb15/topk_20/fold_2/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/moa/hb15/topk_20/fold_3/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/moa/hb15/topk_20/fold_4/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb/topk_1/fold_3/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb/topk_1/fold_4/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb15/topk_1/fold_0/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb15/topk_1/fold_1/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb15/topk_1/fold_2/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb15/topk_1/fold_3/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb15/topk_1/fold_4/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb/topk_10/fold_0/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb/topk_10/fold_1/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb/topk_10/fold_2/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb/topk_10/fold_3/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb/topk_10/fold_4/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/pb/topk_10/fold_0/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/pb/topk_10/fold_1/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/pb/topk_10/fold_2/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/pb/topk_10/fold_3/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/pb/topk_10/fold_4/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb15/topk_10/fold_0/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb15/topk_10/fold_1/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb15/topk_10/fold_2/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb15/topk_10/fold_3/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb15/topk_10/fold_4/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb/topk_20/fold_0/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb/topk_20/fold_1/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb/topk_20/fold_2/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb/topk_20/fold_3/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb/topk_20/fold_4/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/pb/topk_20/fold_0/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/pb/topk_20/fold_1/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/pb/topk_20/fold_2/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/pb/topk_20/fold_3/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/pb/topk_20/fold_4/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb15/topk_20/fold_0/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb15/topk_20/fold_1/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb15/topk_20/fold_2/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb15/topk_20/fold_3/results.pkl
Skipped /home/leostre/Рабочий стол/py-boost/sketchboost-paper/runs/SKETCHBOOST_ALLK/rf1/hb15/topk_20/fold_4/results.pkl

In [79]:
def get_one_field(all_data, field, value, aggfunc=None):
    one_model = all_data[all_data[field] == value]
    index = [c for c in KEYS if c != field]
    one_model.drop(field, axis=1, inplace=True)
    if aggfunc:
        one_model = one_model.groupby(index).aggregate(aggfunc)

    return one_model

In [80]:
import numpy as np 

def agg_mean_std(x):
    return f'{np.mean(x):.2f}±{np.std(x):.2f}'

In [82]:
all_results.to_csv('Andrews_requst.py-boost.py')

In [81]:
get_one_field(all_results, 'model', 'pb', )

/tmp/ipykernel_15152/3224762718.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  one_model.drop(field, axis=1, inplace=True)

,dataset,k,train_time,best_iter,val_pred_time,test_pred_time,test_score,val_score,test_acc,val_acc
5,helena,1,48.688646,8552,0.973593,0.124332,2.589112,2.593546,0.382439,0.380176
6,helena,1,46.106237,8053,0.939651,0.117230,2.587372,2.638382,0.379985,0.371393
7,helena,1,47.672789,8403,0.928763,0.121879,2.589365,2.606174,0.378144,0.379542
8,helena,1,45.073006,7830,0.894623,0.120288,2.584336,2.564528,0.381979,0.382801
9,helena,1,52.348300,8729,1.022483,0.132443,2.586505,2.575187,0.379831,0.381938
19,helena,10,44.281637,5324,0.601603,0.081752,2.596783,2.602021,0.377607,0.375479
20,helena,10,42.142302,5064,0.566437,0.077939,2.597003,2.643713,0.378451,0.369284
21,helena,10,44.016530,5377,0.607105,0.084153,2.600655,2.615579,0.375077,0.379542
22,helena,10,45.152021,5442,0.608850,0.083633,2.592981,2.573941,0.379678,0.379925
23,helena,10,45.652423,5542,0.621823,0.085772,2.594504,2.583807,0.376840,0.383376
29,helena,20,55.659636,5171,0.540082,0.075795,2.600013,2.606152,0.378988,0.375575
30,helena,20,50.762630,4869,0.512352,0.071409,2.598701,2.647130,0.376227,0.368900
31,helena,20,49.963648,4760,0.568755,0.069774,2.601948,2.618222,0.374387,0.376282
32,helena,20,48.410404,4597,0.557694,0.067536,2.595380,2.581512,0.376764,0.380884
33,helena,20,49.584259,4731,0.553261,0.069330,2.598899,2.583917,0.377147,0.380692
39,moa,1,16.489290,2484,0.287153,0.028818,0.016793,0.016374,0.997002,0.997100
40,moa,1,16.679183,2548,0.288755,0.028960,0.016781,0.016274,0.997000,0.997101
41,moa,1,16.731192,2540,0.289919,0.028705,0.016728,0.016355,0.997012,0.997100
42,moa,1,16.693982,2531,0.292111,0.028900,0.016747,0.016042,0.997000,0.997187
43,moa,1,16.984807,2600,0.297469,0.029935,0.016741,0.016226,0.997015,0.997073
49,moa,10,61.813689,1883,0.230312,0.022122,0.016463,0.016032,0.997059,0.997139
50,moa,10,61.492765,1878,0.227076,0.021798,0.016448,0.015946,0.997046,0.997137
51,moa,10,58.600066,1760,0.222230,0.021929,0.016464,0.015994,0.997056,0.997129
52,moa,10,61.328374,1869,0.232871,0.022037,0.016451,0.015741,0.997062,0.997214
53,moa,10,58.974881,1778,0.220172,0.020864,0.016437,0.015899,0.997049,0.997108
59,moa,20,97.391659,1514,0.195389,0.017966,0.016152,0.015729,0.997126,0.997187
60,moa,20,96.877154,1502,0.197248,0.017918,0.016150,0.015594,0.997121,0.997191
61,moa,20,99.663780,1559,0.200912,0.018562,0.016131,0.015687,0.997120,0.997198
62,moa,20,107.131744,1718,0.215621,0.020671,0.016169,0.015472,0.997130,0.997273
63,moa,20,102.894887,1628,0.206280,0.019515,0.016126,0.015611,0.997129,0.997175
67,rf1,1,81.407057,7810,0.848018,0.082270,1.079173,1.131562,0.999414,0.999244
68,rf1,1,192.024247,20000,2.166666,0.219618,1.041645,1.002468,0.999463,0.999392
69,rf1,1,188.892478,19912,2.169500,0.214869,1.027736,1.178327,0.999490,0.999272
70,rf1,1,191.085613,19999,2.199837,0.230400,1.078027,1.239469,0.999465,0.999180
71,rf1,1,192.799448,20000,2.258762,0.224504,0.943134,1.404928,0.999538,0.999121

In [69]:
get_one_field(all_results, 'model', 'hb', )

/tmp/ipykernel_15152/3224762718.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  one_model.drop(field, axis=1, inplace=True)

,dataset,k,train_time,best_iter,val_pred_time,test_pred_time,test_score,val_score,test_acc,val_acc
0,helena,1,143.587237,4171,0.538617,0.063962,2.583761,2.590925,0.379908,0.377109
1,helena,1,133.325150,3835,0.488470,0.059475,2.583203,2.630249,0.381518,0.371297
2,helena,1,132.476053,3797,0.486000,0.058389,2.586114,2.601297,0.376304,0.375611
3,helena,1,130.893056,3744,0.494510,0.057734,2.581511,2.561978,0.378988,0.382418
4,helena,1,139.911396,4042,0.511208,0.062639,2.584221,2.569850,0.378604,0.384048
15,helena,10,142.534079,4120,0.522299,0.063402,2.583960,2.592089,0.380982,0.377109
16,helena,10,137.678344,3966,0.506229,0.060829,2.583655,2.629281,0.379908,0.370914
17,helena,10,132.357692,3797,0.491840,0.059257,2.587305,2.600832,0.376150,0.376570
18,helena,10,142.613365,4088,0.516389,0.064025,2.582460,2.561429,0.376917,0.381267
19,helena,10,141.760166,4022,0.509899,0.062256,2.583181,2.569776,0.378758,0.383472
25,helena,20,134.930904,3799,0.494296,0.059678,2.583643,2.591287,0.378451,0.375959
26,helena,20,138.266687,3910,0.498212,0.061444,2.583718,2.628693,0.379601,0.370818
27,helena,20,136.082183,3838,0.496029,0.060502,2.585589,2.599952,0.376534,0.373981
28,helena,20,132.535068,3728,0.491142,0.058707,2.581447,2.562037,0.376840,0.382034
29,helena,20,141.821042,4058,0.498871,0.060498,2.582922,2.570166,0.378528,0.383281
35,moa,1,743.526777,1094,0.159972,0.013777,0.016029,0.015638,0.997131,0.997186
36,moa,1,754.851855,1118,0.163276,0.014410,0.016009,0.015480,0.997138,0.997210
37,moa,1,776.448456,1164,0.167682,0.014972,0.016023,0.015491,0.997146,0.997206
38,moa,1,781.984991,1150,0.177649,0.014287,0.015997,0.015359,0.997143,0.997262
39,moa,1,751.249224,1083,0.161144,0.013629,0.016009,0.015512,0.997132,0.997175
45,moa,10,756.259161,1091,0.165666,0.015390,0.016031,0.015643,0.997133,0.997185
46,moa,10,764.574970,1122,0.162414,0.013911,0.016001,0.015493,0.997139,0.997201
47,moa,10,788.939867,1150,0.186017,0.016931,0.016021,0.015493,0.997143,0.997208
48,moa,10,791.935066,1180,0.170440,0.014689,0.015999,0.015364,0.997144,0.997270
49,moa,10,758.592493,1115,0.166451,0.014482,0.016010,0.015502,0.997128,0.997174
55,moa,20,725.051849,1033,0.163144,0.014935,0.016040,0.015633,0.997135,0.997189
56,moa,20,771.791725,1103,0.159162,0.013778,0.016008,0.015490,0.997141,0.997203
57,moa,20,777.934520,1146,0.173152,0.014629,0.016023,0.015499,0.997143,0.997207
58,moa,20,832.827555,1150,0.172238,0.016566,0.015997,0.015360,0.997144,0.997263
59,moa,20,790.348741,1162,0.168081,0.014630,0.016011,0.015509,0.997134,0.997180
65,rf1,1,163.926773,10815,1.227053,0.115321,1.082213,1.120452,0.999595,0.999414
66,rf1,1,282.239848,19998,2.209306,0.213778,0.840775,0.867476,0.999709,0.999550
67,rf1,1,279.550573,19998,2.169006,0.213582,0.817898,0.876069,0.999740,0.999673

In [70]:
hb = get_one_field(all_results, 'model', 'hb', 'mean')

/tmp/ipykernel_15152/3224762718.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  one_model.drop(field, axis=1, inplace=True)

In [71]:
pb = get_one_field(all_results, 'model', 'pb', 'mean')

/tmp/ipykernel_15152/3224762718.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  one_model.drop(field, axis=1, inplace=True)

In [72]:
(hb - pb) / pb * 100

             train_time  best_iter  val_pred_time  test_pred_time  test_score  \
dataset k
helena  1    183.544869 -52.873674     -47.074059      -50.955361   -0.138213
        10   215.010020 -25.257019     -15.275829      -25.040573   -0.472698
        20   168.745315 -19.873176      -9.281833      -14.983024   -0.597324
moa     1   4456.271515 -55.845076     -42.990367      -51.090307   -4.443781
        10  1177.358273 -38.285340     -24.868183      -30.662799   -2.673976
        20   673.466225 -29.377604     -17.693828      -21.233964   -0.804675
rf1     1     42.935006  -3.460973      -3.116407       -6.915314  -11.636453

            val_score  test_acc   val_acc
dataset k
helena  1   -0.181214 -0.370863 -0.283161
        10  -0.504295  0.268129  0.091410
        20  -0.650438  0.342006  0.198627
moa     1   -4.666745  0.013310  0.009583
        10  -2.659776  0.008341  0.006235
        20  -0.770505  0.001451  0.000358
rf1     1  -19.866934  0.020708  0.030394

In [73]:
hb

            train_time  best_iter  val_pred_time  test_pred_time  test_score  \
dataset k
helena  1   136.038578     3917.8       0.503761        0.060440    2.583762
        10  139.388729     3998.6       0.509331        0.061954    2.584112
        20  136.727177     3866.6       0.495710        0.060166    2.583464
moa     1   761.612261     1121.8       0.165944        0.014215    0.016013
        10  772.060311     1131.6       0.170198        0.015081    0.016013
        20  779.590878     1118.8       0.167155        0.014908    0.016016
rf1     1   241.905731    16937.0       1.868455        0.180894    0.913629

            val_score  test_acc   val_acc
dataset k
helena  1    2.590860  0.379064  0.378096
        10   2.590681  0.378543  0.377866
        20   2.590427  0.377991  0.377215
moa     1    0.015496  0.997138  0.997208
        10   0.015499  0.997138  0.997208
        20   0.015498  0.997140  0.997209
rf1     1    0.954666  0.999681  0.999546

In [74]:
get_one_field(all_results, 'model', 'hb', agg_mean_std)

/tmp/ipykernel_15152/3224762718.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  one_model.drop(field, axis=1, inplace=True)

              train_time         best_iter val_pred_time test_pred_time  \
dataset k
helena  1    136.04±4.87    3917.80±161.98     0.50±0.02      0.06±0.00
        10   139.39±3.96    3998.60±114.00     0.51±0.01      0.06±0.00
        20   136.73±3.15    3866.60±112.35     0.50±0.00      0.06±0.00
moa     1   761.61±14.94     1121.80±31.21     0.17±0.01      0.01±0.00
        10  772.06±15.28     1131.60±30.65     0.17±0.01      0.02±0.00
        20  779.59±34.61     1118.80±47.31     0.17±0.01      0.01±0.00
rf1     1   241.91±55.15  16937.00±4328.91     1.87±0.45      0.18±0.05

           test_score  val_score   test_acc    val_acc
dataset k
helena  1   2.58±0.00  2.59±0.02  0.38±0.00  0.38±0.00
        10  2.58±0.00  2.59±0.02  0.38±0.00  0.38±0.00
        20  2.58±0.00  2.59±0.02  0.38±0.00  0.38±0.00
moa     1   0.02±0.00  0.02±0.00  1.00±0.00  1.00±0.00
        10  0.02±0.00  0.02±0.00  1.00±0.00  1.00±0.00
        20  0.02±0.00  0.02±0.00  1.00±0.00  1.00±0.00
rf1     1   0.91±0.12  0.95±0.12  1.00±0.00  1.00±0.00

In [75]:
get_one_field(all_results, 'model', 'pb', agg_mean_std)

/tmp/ipykernel_15152/3224762718.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  one_model.drop(field, axis=1, inplace=True)

              train_time         best_iter val_pred_time test_pred_time  \
dataset k
helena  1     47.98±2.52    8313.40±328.38     0.95±0.04      0.12±0.01
        10    44.25±1.21    5349.80±160.33     0.60±0.02      0.08±0.00
        20    50.88±2.51    4825.60±193.23     0.55±0.02      0.07±0.00
moa     1     16.72±0.16     2540.60±37.09     0.29±0.00      0.03±0.00
        10    60.44±1.37     1833.60±53.24     0.23±0.00      0.02±0.00
        20   100.79±3.82     1584.20±80.18     0.20±0.01      0.02±0.00
rf1     1   169.24±43.94  17544.20±4867.22     1.93±0.54      0.19±0.06

           test_score  val_score   test_acc    val_acc
dataset k
helena  1   2.59±0.00  2.60±0.03  0.38±0.00  0.38±0.00
        10  2.60±0.00  2.60±0.02  0.38±0.00  0.38±0.00
        20  2.60±0.00  2.61±0.02  0.38±0.00  0.38±0.00
moa     1   0.02±0.00  0.02±0.00  1.00±0.00  1.00±0.00
        10  0.02±0.00  0.02±0.00  1.00±0.00  1.00±0.00
        20  0.02±0.00  0.02±0.00  1.00±0.00  1.00±0.00
rf1     1   1.03±0.05  1.19±0.13  1.00±0.00  1.00±0.00

In [63]:
get_one_field(all_results, 'model', 'hb15', agg_mean_std)

/tmp/ipykernel_15152/3224762718.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  one_model.drop(field, axis=1, inplace=True)

,,train_time,best_iter,val_pred_time,test_pred_time,test_score,val_score,test_acc,val_acc
dataset,k,,,,,,,,
helena,1,71.02±75.31,1383.40±2045.90,0.31±0.38,0.05±0.05,3.55±0.22,3.55±0.22,0.25±0.02,0.25±0.02